# Generated by Django 5.2.9 on 2025-12-18 07:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_alter_category_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
