# Generated by Django 5.2.9 on 2025-12-18 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_cart_cartitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("add_to_cart", "Add to cart"),
                    ("view_cart", "View Cart"),
                    ("delete_cart", "Delete cart"),
                    ("checkout", "Checkout"),
                ]
            },
        ),
    ]
